### ISSUE TITLE
HmIP-SMI light level 

### ISSUE THREAD

**Issue by michalkolacek** [thkl/homebridge-homematic#245]
Please its possible to fix light level range in homekit ?
The sonsor sending brightness information with values in hunderts units.
In the homekit is set range to 100000 its nearly impossible to set some trigger , because little move with slider set very high values.

**Comment by jhk3** [comment]
Here, my HmIP-SMI works just fine with "homebridge-homematic". In the iOS "Home" App, there are only readings (typically between 0 and 200 LUX are reported by HmIP-SMI in my room, depending on daytime), but no settings for brightness for this device and I do not see an option to set the brightness in the WebUI of the CCU2 either. Perhaps you have a different device?

**Comment by michalkolacek** [comment]
I have the same device ,
If you want do define " turn on lights by move if the brightness is lower then 50 lux"
You need to define it in elgato or some other app (i tried few other and looks the same, thats reason why i mean that the definition of maximum value comes from home kit definition).
You set movement like trigger and brightness like condition.
If you want set the condition it will show you slider where is minimum 0 and maximum 100000.
If you want choose for example 200 you cannt. because the slider need to me moved very little bit .
If the maximum will be set 1000 it will be much more easier.

**Comment by jhk3** [comment]
For me this works just fine through a direct device connection with HmIP-BSM or Hue lights in the WebUI of CCU2 without any issue. I checked the Elgato "Eve" App. Indeed the values that can be chosen to trigger events when defining rules in "Eve" are too high and differ from the brigthness values seen from the sensor in the very same app. It seems like a bug in Eve or in homekit.
BTW, brightness levels similar to HmIP-SMI in Lux are also reported by the hue bmotion sensor. They are correct and should not be changed as this is also the WebUI readout in Lux.

**Comment by michalkolacek** [comment]
I have the problem also in other apps , not only eve.
I do not understand how the values goes true homekit , only suppose that the value comes also with range (max and min possible value).

**Comment by jhk3** [comment]
I checked the rules that can be defined for the hue motion sensor in the "Eve" app from Elgato. This has the same behavior that you described for HmIP-SMI. Both sensors, hue motion and HmIP report in a brightly illuminated rooms about 100 Lux and the eve detection slider goes for both from 1 to 130000.0 "Lux" (as it displays it). Since my hue motion sensor is connected through the Philips hue bridge to iOS homekit, this is cannot be  "homebridge-homematic" issue.

**Comment by michalkolacek** [comment]
I found homekit doc and there is:
100000 Lux like maximum and 0.0001 like minimum in format float.
You are right that there is no error on homebridge-homematic, the homekit range is too big.

Only way in this case is multiply the lux value with 100.
Its there possibility to implement this change ?

**Comment by jhk3** [comment]
I am not the author of the plugin, but in my opinion, the issue got to be fixed in homekit itself, not in the homematic plugin. [As a user I would voice opposition against such a change to the homebridge-homematic plugin; after all it is Lux what homekit reports and it is Lux what it gets from  the plugin].

**Comment by thkl** [comment]
can someone please summerize the current change request ?

**Comment by jhk3** [comment]
The request concerns an issue in Apps like Elgato "Eve" that are based on homekit. In these Apps, homekit rules for automation based on brightness values are difficult to set up, because of the brightness range that is selectable via a slider: 0-130000 Lux. Conventional artificial lightning of rooms is in the range of 0 to 100 Lx. Via the homekit slider , this is difficult to set up values between 0 and 100 Lux, see attached image.
![img_4250](https://user-images.githubusercontent.com/35252324/38073620-21240b7a-332c-11e8-84fc-a0c8d7958f7a.jpg)
The issue does not concern the Homebridge-Homematic plugin as the very same issue exists for the Philips hue motion sensor with brightness detection that is integrated into homekit via the Philips Hue Bridge.

**Comment by thkl** [comment]
so there is nothing to to at my side ? ... sounds great ;)

**Comment by jhk3** [comment]
Apple or Homekit-App developers should fix this by replacing the slider with a field that allows the direct entry of numbers.

**Comment by thkl** [comment]
Ok according due the fact, that i do not own such a device, i am not sure if that works:
i've changed the max lux property for CurrentAmbientLightLevel. If there is anyone who can test this, please xchange /ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js with that https://raw.githubusercontent.com/thkl/homebridge-homematic/develop/ChannelServices/HomeMaticHomeKitMotionDetectorServiceIP.js and check if Eve or the home app takes care about the change of max lux ...

**Comment by jhk3** [comment]
This works. I did not anticipate that this is possible. The only problem that remains that with this type of solution, I cannot distinguish whether I point with my red or my green laser pointer onto the sensor ;)
Max value of 200 would be my preference.  Anyway, quite cool.

**Comment by thkl** [comment]
;o) .. not prob, the line number 48 is where the magic livs .. just change maxValue to 200 ...

so it works and i will close this issue
