### ISSUE TITLE
Geräte übermitteln falschen Status

### ISSUE THREAD

**Issue by weaverprojects** [thkl/homebridge-homematic#311]
HI, seit Version homebridge-homematic v0.0.109 haben die Fenstersensoren nur noch den Status "offen" obwohl sie geschlossen sind. Die Keymatic ändert ihren Zustand immer wenn man die Home App öffnet obwohl die Tür weder geöffnet noch geschlossen wird. Wie komme ich wieder zurück auf die vorhergehende Version. Raspberry PI mit manueller Homebridge Installation.

config:

{
            "platform": "HomeMatic",
            "name": "HomeMatic CCU",
            "ccu_ip": "192.168.2.101",
            "enable_hmip": true,
            "local_port": 9092,
            "filter_device": [],
            "filter_channel": [],
            "outlets": [],
            "doors": [
                "BidCos-RF.OEQ0351499:1"
            ],
            "programs": [],
            "subsection": "HomeKit"
        },

**Comment by rpdever** [comment]
Willkommen im Club, ich habe seit ein paar Wochen bereits das Problem, dass meine Rolladen wohl immer offen sind. Automationen funktionieren trotzdem.

Ich würde mich auch über eine Lösung freuen

**Comment by thkl** [comment]
Ich werfe mal einen Blick drauf.

**Comment by weaverprojects** [comment]
Ich habe das Problem lösen können indem ich das Homematic Keymatic gelöscht habe. Seitdem übertragen die Homematic IP Geräte wieder den richtigen Status.

**Comment by thkl** [comment]
Whaat ? Die Geräte haben nichts miteinander zu tun. Ich habe leider keine KM zum Test. 

Meine HM und HmIp Kontakte funktionieren problemlos.  Die Änderungen werden in Echtzeit übertragen.  Einzig was mir aufgefallen ist, das wenn die Verbindung zwischen CCU und HomeKit, durch was auch immer, ausfällt der Zustand erst wieder stimmt wenn die Kontakte einmal geschaltet haben.  Hier könnte ich ggf einen Reinit machen wenn ich die Verbindung zur CCU wieder neu aufbaue.

**Comment by rpdever** [comment]
Dann habe ich wohl einen ganz anderen Fehler: Unabhängig ob ich die Rolladen manuell am Aktor schalte oder nicht, ändert sich der Status nach etwa 3sek wieder auf offen. Wenn ich dann long-press darauf machen und den Schieber bewege, wird alles wie gewünscht ausgeführt. Ich werde wohl mal auf eine Version von vor paar Monaten zurück gehen, dort ging es einwandfrei. Hat dies Auswirkungen auf das System? Also kann es passieren dass ich die Geräte neu in HomeKit einbinden muss?

Wenn ich irgendetwas testen muss / soll, keine Problem, ich habe einen zweiten PI für meine App Programmierung.

**Comment by nicoh88** [comment]
Habe hier auch das Problem, dass für die HmIP-FROLL (Rollläden Unterputz) der falsche Status angezeigt wird.

**Comment by rpdever** [comment]
Hi zusammen, ich habe mein Problem teils gelöst. Als ich für einen Freund ein Funkmodul zusammengelötet hatte, wollte ich dieses natürlich gleich testen. Und siehe da, auf einmal steht da geschlossen. Also habe ich bei meinem nochmal nachgelötet und das Problem ist nun fast behoben. Fast. Manchmal steht trotzdem etwas falsches da, etwa dann, wenn man das System neustartet oder das runterfahren zu lange dauert.

**Comment by rpdever** [comment]
Ich nochmal. Leider war mein oberer Post ein falscher Alarm! Wenige Zeit später, gleiches Problem, egal welches Funkmodul. Dies zeigte sich dann auch, als ich ein neues Funkmodul auf einem neuen PI mit neuer Konfiguration installierte. Dort habe ich einen Doppel-Licht-Aktor angelernt. Der Status wurde nicht mit dem aktuellen abgeglichen und verschwand nach dem Schließen der App. 

Also alle letzten Versionen durchgegangen, tausend mal neu angelernt und siehe da : NPM VERSION  0.0.96 läuft sowohl dort als auch bei mir ohne Fehler. Alles so wie es soll. BITTE gehe die Commits nochmal durch irgendwo danach liegt ein gravierender Aktor übergreifender Fehler!

Für genauere Informationen stehe ich natürlich zur Verfügung.

An alle anderen mit dem Problem, versucht folgendes:

- Homebridge stoppen

- sudo npm i homebridge-homematic@0.0.96 -g

Eine Deinstallation ist nicht nötig, ein zurückkehren auf eine neuere Version ebenfalls. Ich musste meine Geräte bei dieser Version nicht neu einbinden.

**Comment by m-rossi** [comment]
Ich hatte das Problem gerade auch und bin über diese Issue gestolpert und war kurz davor die ältere Version einzuspielen. Habe aber vorher noch ein paar andere Pakete umkonfiguriert und dabei auch homebridge ein paar Mal neu gestartet und auf einmal funktionieren die Fensterkontakte wieder und übermitteln (aktuell) zuverlässig ihren Status.

**Comment by m-rossi** [comment]
Ok zu früh gefreut. Gestern wurden die Kontakte nicht aktualisiert. Nach einen Neustart von homebridge ist alles wieder normal.

**Comment by rpdever** [comment]
Hallo m-rossi, brauchst du jetzt noch was oder hat es sich erledigt? Ich pack trotzdem mal den Output rein:

pi@mainraspberry:~ $ npm outdated -g
Package                             Current  Wanted   Latest  Location
homebridge                           0.4.42  0.4.45   0.4.45
homebridge-homematic                 0.0.96  0.0.96  0.0.109
homebridge-hue                        0.9.2   0.9.9   0.10.5
homebridge-platform-wemo              1.3.6   1.3.8    1.3.8
homebridge-raspberrypi-temperature    0.0.6   0.0.6    0.0.7
homebridge-wol                        3.2.2   3.2.4    3.2.4
n                                    2.1.10  2.1.12   2.1.12
npm                                   5.6.0  5.10.0    6.4.1

**Comment by wernergauer** [comment]
Ich hatte das gleiche Problem. 
sudo npm install -g homebridge-homematic hat mir die 0.0.109 installiert. Damit lief keiner meiner Fenstersensoren. Bin dann zurück auf 0.0.96 und alles war prima. Heute mal etwas geforscht und gesehen, dass mein NodeJs mit 4.5 recht alt war. Bin nun auf 8.11 und siehe da - die 0.0.109 sieht wieder den richtigen Status der Sensoren.

Fazit: Upgrade von NodeJS und NPM

**Comment by wernergauer** [comment]
Ich hatte das gleiche Problem.
sudo npm install -g homebridge-homematic hat mir die 0.0.109 installiert. Damit lief keiner meiner Fenstersensoren. Bin dann zurück auf 0.0.96 und alles war prima. Heute mal etwas geforscht und gesehen, dass mein NodeJs mit 4.5 recht alt war. Bin nun auf 8.11 und siehe da - die 0.0.109 sieht wieder den richtigen Status der Sensoren.

Fazit: Upgrade von NodeJS und NPM

**Comment by Mountain-wg** [comment]
Ich hatte das gleiche Problem.
sudo npm install -g homebridge-homematic hat mir die 0.0.109 installiert. Damit lief keiner meiner Fenstersensoren. Bin dann zurück auf 0.0.96 und alles war prima. Heute mal etwas geforscht und gesehen, dass mein NodeJs mit 4.5 recht alt war. Bin nun auf 8.11 und siehe da - die 0.0.109 sieht wieder den richtigen Status der Sensoren.

Fazit: Upgrade von NodeJS und NPM

**Comment by m-rossi** [comment]
@rpdever ich würde mal homebridge, homebridge-homematic und npm updaten und schauen ob es zumindest temporär, wie bei mir, das Problem löst.

@Mountain-wg nodejs ist bei mir auf Version 8.12 und trotzdem hab ich das Problem kürzlich gesehen.

**Comment by rpdever** [comment]
Erstmal sorry für die späte Meldung. Ich wollte erstmal das System wieder etwas austesten. Ich habe wie @m-rossi gesagt hat, die drei "Dinger" geupdated. Seitdem ich dies vor ein paar Tagen gemacht hatte, habe ich keine Probleme mehr. Ich werde das jetzt noch ein paar Tage beobachten und dann nochmal Rückmeldung geben!

@thkl Ich würde dir dann empfehlen, einen Vermerk im REEDME zu hinterlegen, indem steht, dass man Homebridge, npm und Homebridge-homematic aktualisieren soll um einen reibungslosen Betrieb zu gewährleisten. Ich habe Kumpels gefragt die ebenfalls das Plugin benutzen, diese haben mir von ähnlichen Problemen berichtet.

Vielen Dank für die Mühen und ich hoffe dass allen die derartige Probleme hatten, nun geholfen ist!

Schönen Feiertag euch allen!

**Comment by mrhund** [comment]
Hallo erstmal, ich verwende das Plugin jetzt schon seit einigen Monaten, danke für die grandiose Arbeit!

Mein Input zu dem Thema:
Ich hab gestern ein wenig rumgespielt, weil ich den ThermometerService zum Laufen bringen wollte.
Bisher war ich auf V109, nach dem Update auf die Master Version hatte ich aber das Problem, dass die Rolläden, aber auch die Schalter den falschen Status übermittelt haben. Bei den Rolläden hab ich bemerkt, dass der Status immer dann nicht stimmt, wenn die Position irgendwo zwischen 0 und 100% ist (also halb offen zb, nicht in Bewegung), bei den Schaltern konnte ich kein Muster erkennen.
homebridge, homebridge-homematic und npm sind alle auf dem neuesten Stand, node ist Version 10.2.
Bin jetzt wieder auf V109 gegangen, Probleme sind soweit wieder weg.

Ich fürchte also, dass das Problem damit nicht behoben ist :/

**Comment by rpdever** [comment]
Danke für deine Rückmeldung. Ich denke wir können nun definitiv sagen, dass es keine Einzelfehler sind. Bei uns läuft eigentlich alles so wie es soll (mit den Versionen wie oben beschreiben), allerdings gebe ich zu, dass wir die Rolladen im Moment nicht auf Prozentwerte fahren lassen, das werde ich später nochmal überprüfen. Das mit den Schaltern ist interessant, ein Bekannter von mir, für den ich das ganze mache, besitzt auch welche und ist genau auf den selben Versionen wie ich und hat keine Probleme.

Vielleicht sollte @thkl sich die Sache nochmal genauer anschauen.

Auch wenn ich Probleme mit diesem Plugin habe/hatte, muss ich mich wirklich auch mal bedanken. Man kann ja hier wirklich von einer herausragenden ehrenamtlichen Tätigkeit sprechen. Ohne dieses Plugin gäbe es allein wohl kaum Produkte im Rolladen Segment, die man in HomeKit nutzen kann.

Schönes Wochenende!

**Comment by royalflashii** [comment]
Habe momentan das problem auch mit einem Unterputz Rolladenkator von HM. Dort wird mir immer der Status öffnen angezeigt. die anderne Unterputz Rolladenaktoren von HmIP zeigen immer geschlossen an. Bin etwas Ratlos weil ich auch videodoorbell benutze und daher auf die version 109 angewiesen bin.

**Comment by Ron0815** [comment]
Hallo zusammen!
Ich habe in etwa dasselbe Problem, wie in den obigen Posts beschrieben. Ich muss vorwegschicken, dass ich absolut keine Ahnung vom Programmieren habe und gerade mit einem Raspberry Pi 3 B+ und Homematic-Geräten erstmals in das Thma  einsteige. Diese würde ich gerne über Apple Homekit und AppleTV 4 steuern. Die Homebridge habe ich bereits installiert (über ein All-in-One-Image, bei dem auch ioBroker eingebunden ist). Ich suche schon seit Tagen nach dem Grund für die Funktionsstörungen, habe schon die verschiedennsten Foren durchforstet und die Lösungsvorschläge ausprobiert, finde aber leider nichts, weshalb Ihr meine letzte Hoffnung seid.

Nun zu meinem Problem: Homekit zeigt bei den Homematic-Geräten nicht die aktuellen Zustände. Rolladen werden als geschlossen oder geöffnet angezeigt, obwohl das Gegenteil der Fall ist; Heizkörperthermostate zeigen nicht die aktuellen Heizeinstellungen bzw. Temperaturvorgaben. AppleTV vom Strom nehmen und neustarten half nicht. Ich hatte auch schon befürchtet, dass Einstellungen in ioBroker stören könnten, und habe das Programm deshalb gestoppt. Anschließend Homebridge neugestartet, keine Besserung. Über die Konsole war dann im Startprotokoll von Homebridge folgendes zu lesen (rot hervorgehoben):

[2019-1-7 21:16:56] [HomeMatic CCU3] ****************************************************************************************************************************
[2019-1-7 21:16:56] [HomeMatic CCU3] *  Sorry the local port 9090 on your system is in use. Please make sure, that no other instance of this plugin is running.
[2019-1-7 21:16:56] [HomeMatic CCU3] *  you may change the initial port with the config setting for local_port in your config.json 
[2019-1-7 21:16:56] [HomeMatic CCU3] *  giving up ... the homematic plugin is not able to listen for ccu events on BidCos-RF. until you fix this. 
[2019-1-7 21:16:56] [Home

Verstehe ich das richtig, dass ich feststellen muss, welcher Dienst bzw. welche Instanz den Port 9090 nutzt, und diese/n beenden? Aber wie stelle ich fest, welche Instanz das ist? Hat jemand einen Rat? 

Zusatzfrage: Die Weboberfläche der Homebridge sollte ich an sich üver die IP-Adresse des Raspberry und den Port 8083 erreichen können. Das funktioniert aber nicht. Hängt dieses mit dem vorbeschriebenen Problem zusammen? Und muss ich eventuell den Port 9090 in 8083 ändern? Oder werfe ich hier komplett was durcheinander?

Fragen über Fragen ...

Für Hilfe wäre ich sehr dankbar!!!

VG
R

**Comment by royalflashii** [comment]
Also diese Fehlermeldung hatte ich wenn der Dienst doppelt ausgefüttert wurde also die home ridge. Probier mal in die Konsole einzugeben “sudo /etc/init.d/homebridge stop” und dann “homebridge -D” dann siehst du den gesamten log was vor sich geht. Wenn du dann den Dienst starten willst musst du “sudo /etc/init.d/homebridge start” eingeben. Oder einfach an deinem raspi den Strom ziehen und 10 Sec warten, wenn du den autostart richtig eingerichtet hast.

**Comment by Ron0815** [comment]
Okay, das mache ich heute Abend gleich mal und werde dann berichten.

**Comment by Ron0815** [comment]
Ne, hat leider nicht funktioniert. Es kam anschließend folgende Fehlermeldung:

Unable to parse live ccu data. Will try cache if there is one. If you want to know what, start homebridge in debug mode -> DEBUG=* homebridge -D

Habe dann AppleTV einmal vom Strom genommen, überflüssige Geräte aus der AppleID gelöscht und schließlich noch einmal den RasPi neu gestartet. Nichts half. Homebridge synchronisiert nicht die Zustände der Geräte. Ich kann sie auch nicht mehr steuern, obwohl die Buttons aktualisiert werden und anschließend wieder aktiv sind. Auch die Fehlermeldung im Terminal, dass der Port 9090 von einer anderen Instanz genutzt wird, taucht wieder auf. Ich steh völlig auf dem Schlauch.

**Comment by royalflashii** [comment]
Mhm also dann kann ich dir mal empfehlen dein Homematic-homebridge Plugin zu updaten, steht hier im Wiki, ansonsten dann einfach nochmal komplett neu aufsetzten. Bei mir làuft sie einwandfrei. Musste sie auch schon mal neu aufsetzen weil ich so ein àhnlichen Fehler hatte... kam auch zu keiner Lösung weil ich auch nicht so die Ahnung vom programmieren habe. Zum aufsetzten von der kann ich die Seite Technik Kram.net wärmstens empfehlen

**Comment by mrhund** [comment]
> 
> 
> Hallo erstmal, ich verwende das Plugin jetzt schon seit einigen Monaten, danke für die grandiose Arbeit!
> 
> Mein Input zu dem Thema:
> Ich hab gestern ein wenig rumgespielt, weil ich den ThermometerService zum Laufen bringen wollte.
> Bisher war ich auf V109, nach dem Update auf die Master Version hatte ich aber das Problem, dass die Rolläden, aber auch die Schalter den falschen Status übermittelt haben. Bei den Rolläden hab ich bemerkt, dass der Status immer dann nicht stimmt, wenn die Position irgendwo zwischen 0 und 100% ist (also halb offen zb, nicht in Bewegung), bei den Schaltern konnte ich kein Muster erkennen.
> homebridge, homebridge-homematic und npm sind alle auf dem neuesten Stand, node ist Version 10.2.
> Bin jetzt wieder auf V109 gegangen, Probleme sind soweit wieder weg.
> 
> Ich fürchte also, dass das Problem damit nicht behoben ist :/

Hallo!
Mit dem aktuellen DEV branch liefern alle meine Geräte nun korrekte Stati, bis auf die Rollladenaktoren (nicht IP), die spielen völlig verrückt. Es wird noch immer ein falscher Status angezeigt, aber auch beim Bewegen springen sie wirr zwischen unterschiedlichen Zuständen hin und her - auch physisch.

` EventedHTTPServer [::ffff:10.0.0.15] HTTP request: /characteristics +26s
  HAPServer [CC:22:3D:E3:DE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":13,"iid":11,"value":89}] +3ms
  Accessory [Homebridge] Setting Characteristic "Target Position" to value 89 +2ms
  EventedHTTPServer [::ffff:10.0.0.15] Muting event '13.11' notification for this connection since it originated here. +5ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":89}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.15] HTTP Response is finished +9ms
  EventedHTTPServer [::ffff:10.0.0.15] HTTP request: /characteristics +61ms
  HAPServer [CC:22:3D:E3:DE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":13,"iid":11,"value":88}] +2ms
  Accessory [Homebridge] Setting Characteristic "Target Position" to value 88 +2ms
  EventedHTTPServer [::ffff:10.0.0.15] Muting event '13.11' notification for this connection since it originated here. +3ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":88}]} +1ms
  EventedHTTPServer [::ffff:10.0.0.15] HTTP Response is finished +5ms
[2019-3-14 11:10:45] [RaspberryMatic] (Rpc) Send [object Object] to LEVEL at BidCos-RF.NEQ0991354:1 type object
[2019-3-14 11:10:45] [RaspberryMatic] routing via rf xmlrpc
[2019-3-14 11:10:45] [RaspberryMatic] XMLRpc setValue BidCos-RF.NEQ0991354:1 LEVEL [object Object]
[2019-3-14 11:10:45] [RaspberryMatic] RPC setValue Call for NEQ0991354:1 LEVEL Value [object Object] Type object
[2019-3-14 11:10:45] [RaspberryMatic] RPC setValue (NEQ0991354:1 LEVEL) Response "" Errors: null
[2019-3-14 11:10:45] [RaspberryMatic] fallback routing via rega
[2019-3-14 11:10:45] [RaspberryMatic] rega.setvalue BidCos-RF.NEQ0991354:1.LEVEL [object Object]
[2019-3-14 11:10:45] [RaspberryMatic] Rega SetValue 0.88 of BidCos-RF.NEQ0991354:1.LEVEL
[2019-3-14 11:10:45] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:45] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 LEVEL with value 0.76
[2019-3-14 11:10:45] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":76}]} +967ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":76}]} +4ms
[2019-3-14 11:10:45] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:45] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 WORKING with value true
[2019-3-14 11:10:45] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:45] [RaspberryMatic] Skip update because of working flag (true) or IsNull(true)
[2019-3-14 11:10:45] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 DIRECTION with value 1
[2019-3-14 11:10:45] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:45] [RaspberryMatic] Skip update because of working flag (true) or IsNull(1)
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.12' with data: {"characteristics":[{"aid":13,"iid":12,"value":0}]} +41ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.12' with data: {"characteristics":[{"aid":13,"iid":12,"value":0}]} +4ms
[2019-3-14 11:10:45] [RaspberryMatic] Skip update because of working flag (true) or IsNull(1)
[2019-3-14 11:10:45] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:45] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 LEVEL with value 0.775
[2019-3-14 11:10:45] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:45] [RaspberryMatic] Skip update because of working flag (true) or IsNull(77.5)
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.10' with data: {"characteristics":[{"aid":13,"iid":10,"value":77}]} +185ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.10' with data: {"characteristics":[{"aid":13,"iid":10,"value":77}]} +2ms
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":77}]} +3ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":77}]} +2ms
[2019-3-14 11:10:45] [RaspberryMatic] Skip update because of working flag (true) or IsNull(77.5)
  EventedHTTPServer [::ffff:10.0.0.15] HTTP request: /characteristics +95ms
  HAPServer [CC:22:3D:E3:DE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":13,"iid":11,"value":76}] +1ms
  Accessory [Homebridge] Setting Characteristic "Target Position" to value 76 +1ms
  EventedHTTPServer [::ffff:10.0.0.15] Muting event '13.11' notification for this connection since it originated here. +1ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":76}]} +0ms
  EventedHTTPServer [::ffff:10.0.0.15] HTTP Response is finished +3ms
[2019-3-14 11:10:46] [RaspberryMatic] (Rpc) Send [object Object] to LEVEL at BidCos-RF.NEQ0991354:1 type object
[2019-3-14 11:10:46] [RaspberryMatic] routing via rf xmlrpc
[2019-3-14 11:10:46] [RaspberryMatic] XMLRpc setValue BidCos-RF.NEQ0991354:1 LEVEL [object Object]
[2019-3-14 11:10:46] [RaspberryMatic] RPC setValue Call for NEQ0991354:1 LEVEL Value [object Object] Type object
[2019-3-14 11:10:46] [Fernsehgerät] webOS - connecting to TV
[2019-3-14 11:10:46] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:46] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 LEVEL with value 0.835
[2019-3-14 11:10:46] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:46] [RaspberryMatic] Skip update because of working flag (true) or IsNull(83.5)
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.10' with data: {"characteristics":[{"aid":13,"iid":10,"value":83}]} +953ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.10' with data: {"characteristics":[{"aid":13,"iid":10,"value":83}]} +3ms
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":83}]} +4ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":83}]} +3ms
[2019-3-14 11:10:46] [RaspberryMatic] Skip update because of working flag (true) or IsNull(83.5)
[2019-3-14 11:10:46] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:46] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 DIRECTION with value 2
[2019-3-14 11:10:46] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:46] [RaspberryMatic] Skip update because of working flag (true) or IsNull(2)
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.12' with data: {"characteristics":[{"aid":13,"iid":12,"value":1}]} +28ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.12' with data: {"characteristics":[{"aid":13,"iid":12,"value":1}]} +3ms
[2019-3-14 11:10:46] [RaspberryMatic] Skip update because of working flag (true) or IsNull(2)
[2019-3-14 11:10:46] [RaspberryMatic] RPC setValue (NEQ0991354:1 LEVEL) Response "" Errors: null
[2019-3-14 11:10:46] [RaspberryMatic] fallback routing via rega
[2019-3-14 11:10:46] [RaspberryMatic] rega.setvalue BidCos-RF.NEQ0991354:1.LEVEL [object Object]
[2019-3-14 11:10:46] [RaspberryMatic] Rega SetValue 0.76 of BidCos-RF.NEQ0991354:1.LEVEL
[2019-3-14 11:10:46] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:46] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 WORKING with value true
[2019-3-14 11:10:46] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:46] [RaspberryMatic] Skip update because of working flag (true) or IsNull(true)
  EventedHTTPServer [::ffff:10.0.0.15] HTTP request: /characteristics +347ms
  HAPServer [CC:22:3D:E3:DE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":13,"iid":11,"value":83}] +2ms
  Accessory [Homebridge] Setting Characteristic "Target Position" to value 83 +1ms
  EventedHTTPServer [::ffff:10.0.0.15] HTTP Response is finished +2ms
[2019-3-14 11:10:47] [RaspberryMatic] (Rpc) Send [object Object] to LEVEL at BidCos-RF.NEQ0991354:1 type object
[2019-3-14 11:10:47] [RaspberryMatic] routing via rf xmlrpc
[2019-3-14 11:10:47] [RaspberryMatic] XMLRpc setValue BidCos-RF.NEQ0991354:1 LEVEL [object Object]
[2019-3-14 11:10:47] [RaspberryMatic] RPC setValue Call for NEQ0991354:1 LEVEL Value [object Object] Type object
[2019-3-14 11:10:47] [RaspberryMatic] rpc <- system.multicall on BidCos-RF. (null)
[2019-3-14 11:10:47] [RaspberryMatic] RPC event for BidCos-RF.NEQ0991354:1 LEVEL with value 0.785
[2019-3-14 11:10:47] [RaspberryMatic] Accessory RLA SZI 1 found -> Send Event
[2019-3-14 11:10:47] [RaspberryMatic] Skip update because of working flag (true) or IsNull(78.5)
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.10' with data: {"characteristics":[{"aid":13,"iid":10,"value":78}]} +941ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.10' with data: {"characteristics":[{"aid":13,"iid":10,"value":78}]} +4ms
  EventedHTTPServer [::ffff:10.0.0.15] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":78}]} +4ms
  EventedHTTPServer [::ffff:10.0.0.28] Sending HTTP event '13.11' with data: {"characteristics":[{"aid":13,"iid":11,"value":78}]} +3ms
`
Ich konnte das Problem lösen, in dem ich nur die Datei "HomeMaticHomeKitBlindService.js" gegen die des Releases 109 getauscht habe, da geht alles. Leider konnte ich nicht rausfinden, was da den Unterschied macht :(

Zwei Sachen dazu:
- Hat sonst keiner das Problem?
- Vl. sieht wer in den Log-Files das Problem.

**Comment by EricCLP** [comment]
Hallo, ich habe exakt das gleiche Problem. Die Homebridge übermittelt Aufgaben vollkommen zuverlässig, aber Rolläden werden immer als „geschlossen“ angezeigt. Scheint sich also tatsächlich ein systematisches Problem zu sein, um das man sich kümmern könnte. Bin gerne bereit, alle notwendigen Infos zur Klärung beizutragen. Ich müsste nur wissen, was dafür benötigt wird.
