### ISSUE TITLE
Lights showing wrong status since CCU2 update

### ISSUE THREAD

**Issue by peterbaumert** [thkl/homebridge-homematic#67]
Since the newest CCU2 update, my light sometimes show the wrong status.
Is there any way to debug this?

Kind Regards
Pete

**Comment by thkl** [comment]
hmm this is a little special to debug ... can you reproduce the issue ?

**Comment by peterbaumert** [comment]
It happens quite often, but sadly I couldn't reproduce it on purpose :/

**Comment by peterbaumert** [comment]
Could this happen when the CCU restarts but homebridge doesn't and loses the rpc callbacks?

**Comment by peterbaumert** [comment]
Ok figured it happens if I turn on the lights with the switch. It seems like it doesn't send a "notice" to the homebridge, yet Thermostats are working if I change them at the device itself.

**Comment by thkl** [comment]
ok can you name the type of the homematic device please .. HM-....

**Comment by peterbaumert** [comment]
It's HM-LC-Sw1PBU-FM

**Comment by thkl** [comment]
hmm i had an issue on RGBW Devices. But normal Switches should work. 
i have some of that SWITCH Actors at dev and also productiv site and all of them are working just well.
You may start homebridge in debug mode -> DEBUG=* homebridge -D  
after a lot of log there should be an event on every time you flip the switch like that : 

>  HomeMaticRPC RPC event for BidCos-RF.[SerialNumber]:1 STATE with value false +0ms
>   EventedHTTPServer [::ffff:192.168.178.37] Sending HTTP event '2.9' with data: {"characteristics":[{"aid":2,"iid":9,"value":false}]} +51s
 
First line is the CCU Event for that device .. second the homekit event

**Comment by gernot1972** [comment]
Maybe I can bring some light into this issue, because I discovered following issue:
If you make a Program to switch on or of an Actor, Homebridge does not respond correctly!

If you want to reproduce: Please make a little program in WebUI to switch on a light, say for 30seconds and see if homebridge reacts in the status - in my installation it does NOT :-(

Can you confirm this issue?
On the other hand I have some actors who are switched on for a few minutes (like a pump) and in homebridge it is still on and never is switched off, although they are not switched on anymore.

So this is a severe issue, because I (and Siri) never know if the actors are on or off :-(

**Comment by gernot1972** [comment]
just restarted the bridge and now this happens:
after running the program with the On duration of the actor it keeps turned on in iOSHome but was off.
This is exactly what happens with all my lights, or plugs with a set on duration - the off status is not recognized.

**Comment by nobiman** [comment]
It looks as if actuators are switched to on-state with a time limit (for example from a motion detector), the stateChange to "Off" is not correctly recognized by the homebridge?!?!?

**Comment by gernot1972** [comment]
exactly!
Same issue on Highcharts, Pocketcontrol and so on! 
could be a motion detector or a program😐

Sent from a mobile device. I appologize for the brevity and typos.

**Comment by thkl** [comment]
AH ok , i can confirm this issue, but i am not able to fix that. Background:the homebridge module ignores all state changes if the "Working" flag of a channel is set to true, if the flag turns to false, the last known state is set to homekit ... this is to prevent the homekit app from flickering when the level of a dimmer is changed....  when you setup a actor with an ON_TIME the working flag is true while this time ... so the homebridge module ignores all state changes ...

**Comment by gernot1972** [comment]
maybe there is a solution for this with the ontime in the Homekit devices?

Sent from a mobile device. I appologize for the brevity and typos.

**Comment by thkl** [comment]
Nope, the ccu sends only working and state messages when the actor is turned on or off ... currently i do not have a good idea to fix this without breaking the dimmer ...

**Comment by gernot1972** [comment]
So in a first approach is it possible to fix the other actors who are no dimmers - so in first attempt it could be a limitation that you cannot use an on-time for dimmers… or have to do an automation not in WEBUI for dimmers.
Best, Gernot

**Comment by nobiman** [comment]
For me, the one and only reason to use homebridge, is to control my home-automation with siri. 
So, in my opinion this is not a very dramatic issue, rather a cosmetic problem because siri does no status-checks before a component is switched to the desired state, she simply sends the desired command to the device. And if I want to know whether the lights in the livingroom are on, I only have to take a look, but do not need to ask siri ;) And ... I don't think that the Home-App is the right piece of software to solve  automation problems, its only a simple command interface...

... just my 2 cents

**Comment by gernot1972** [comment]
You are absolutely right BUT there are a few things to consider the Home app for visualization as well. First, because you can easily invite guests to have some control of your home.
Second: it becomes a pretty little Interface for the family easy to manage. And third: you only need to have the important devices for control by your family members...
So in future I want to use this Interface also to see the status. And I think we should not make compromises about wrong status displayed for such a simple thing like a plug or lamp 😉.
And of course Automation should not run in this app- this would only be a workaround.

Sent from a mobile device. I appologize for the brevity and typos.

**Comment by thkl** [comment]
ok i've updated the plugin and added a flag to the switch service to ignore that "working" behavior.

**Comment by gernot1972** [comment]
Yess😄 Thanks a lot!

Sent from a mobile device. I appologize for the brevity and typos.
